export const experienceTechnologies = {
  portfolio: ["Astro.js", "Svelte.js", "Tailwindcss", "Shadcn", "v0"],
  gma: [
    "Next.js",
    "TypeScript",
    "Tailwindcss",
    "Ruby on Rails",
    "PostgreSQL",
    "Vercel",
    "Railway",
    "Docker",
    "HeroUI",
    "Lucidchart",
    "TDD",
  ],
  eddu: [
    "Next.js",
    "TypeScript",
    "Tailwindcss",
    "Nodejs",
    "PostgreSQL",
    "Google Cloud Platform",
    "Docker",
    "HeroUI",
    "Lucidchart",
  ],
};
